@api = http://localhost:5000

GET {{api}}/videos
################################
GET {{api}}/videos/602b828927c44c20882
#################################
POST {{api}}/videos
Content-Type: application/json

{
    "url" :"https://www.youtube.com/watch?v=f687hBjwFcM",
    "title": "React Hook Tutorial",
    "description": "This shows the use of react hooks"
}
################################
PUT {{api}}/videos/602b8371f1e75b05c8159737
Content-Type: application/json

{
    "url" :"https://www.youtube.com/watch?v=f687hBjwFcM",
    "title": "React Main Hook Tutorial",
    "description": "This shows the use of react hooks"
}
################################
DELETE {{api}}/videos/602b828927c44c20882aa4dc